#!/usr/bin/env bash

if [[ -z $1 ]]
then
	login='root'
else
	login=$1
fi

broadcast=$(ip a | awk '$1 == "inet" && $4 !~ /(^127|host)/ { print $4"/24" }' | uniq)

RED='\033[0;31m'
GRAY='\033[0;37m'
GREEN='\033[0;32m'
NC='\033[0m'

printf "${GRAY}Executing nmap on the subnets: ${RED}\n$broadcast\n"

candidates=$(
for brdip in ${broadcast}; do 
	nmap -sP $brdip | awk '$2 == "scan" { print $5 }'
done)

connect_id=1

echo

while true
do
	printf "${GRAY}Found the following candidates:\n"

	counter=1

	for candidate in ${candidates}; do
		printf "${GRAY}$counter. ${GREEN}$candidate\n"
		((counter=counter+1))
	done

	printf "${GRAY}0. Exit the script\n"

	printf "${NC}\nChoose one to connect: "
	read connect_id

	if [[ $connect_id -eq 0 ]]
	then
		exit 0
	fi

	counter=1

	for ip in ${candidates}; do
		if [[ $counter -eq $connect_id ]]
		then
			ssh -q $login@$ip
		else
			((counter=counter+1))
		fi
	done

	clear
done